// <auto-generated />
using System;
using CvForge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CvForge.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912032516_AddUserProfileInfo")]
    partial class AddUserProfileInfo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CvForge.Api.Domain.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CvForge.Api.Domain.Cv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("Cvs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CvForge.Api.Domain.AppUser", b =>
                {
                    b.OwnsOne("CvForge.Api.Domain.PersonalInfo", "ProfileInfo", b1 =>
                        {
                            b1.Property<string>("AppUserId");

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("Email")
                                .IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired();

                            b1.Property<string>("GitHub")
                                .IsRequired();

                            b1.Property<string>("JobTitle")
                                .IsRequired();

                            b1.Property<string>("LastName")
                                .IsRequired();

                            b1.Property<string>("LinkedIn")
                                .IsRequired();

                            b1.Property<string>("Phone")
                                .IsRequired();

                            b1.Property<string>("PhotoUrl");

                            b1.Property<string>("Portfolio")
                                .IsRequired();

                            b1.Property<string>("Website")
                                .IsRequired();

                            b1.HasKey("AppUserId");

                            b1.ToTable("AspNetUsers");

                            b1
                                .ToJson("ProfileInfo")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AppUserId");
                        });

                    b.Navigation("ProfileInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("CvForge.Api.Domain.Cv", b =>
                {
                    b.HasOne("CvForge.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CvForge.Api.Domain.CvDocument", "Document", b1 =>
                        {
                            b1.Property<Guid>("CvId");

                            b1.PrimitiveCollection<string>("Interests")
                                .IsRequired();

                            b1.Property<string>("Summary")
                                .IsRequired();

                            b1.Property<string>("TemplateKey")
                                .IsRequired();

                            b1.HasKey("CvId");

                            b1.ToTable("Cvs");

                            b1
                                .ToJson("Document")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("CvId");

                            b1.OwnsMany("CvForge.Api.Domain.Certification", "Certifications", b2 =>
                                {
                                    b2.Property<Guid>("CvDocumentCvId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Date")
                                        .IsRequired();

                                    b2.Property<string>("Issuer")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Url")
                                        .IsRequired();

                                    b2.HasKey("CvDocumentCvId", "__synthesizedOrdinal");

                                    b2.ToTable("Cvs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvDocumentCvId");
                                });

                            b1.OwnsOne("CvForge.Api.Domain.PersonalInfo", "PersonalInfo", b2 =>
                                {
                                    b2.Property<Guid>("CvDocumentCvId");

                                    b2.Property<string>("City")
                                        .IsRequired();

                                    b2.Property<string>("Country")
                                        .IsRequired();

                                    b2.Property<string>("Email")
                                        .IsRequired();

                                    b2.Property<string>("FirstName")
                                        .IsRequired();

                                    b2.Property<string>("GitHub")
                                        .IsRequired();

                                    b2.Property<string>("JobTitle")
                                        .IsRequired();

                                    b2.Property<string>("LastName")
                                        .IsRequired();

                                    b2.Property<string>("LinkedIn")
                                        .IsRequired();

                                    b2.Property<string>("Phone")
                                        .IsRequired();

                                    b2.Property<string>("PhotoUrl");

                                    b2.Property<string>("Portfolio")
                                        .IsRequired();

                                    b2.Property<string>("Website")
                                        .IsRequired();

                                    b2.HasKey("CvDocumentCvId");

                                    b2.ToTable("Cvs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvDocumentCvId");
                                });

                            b1.OwnsOne("CvForge.Api.Domain.CvSettings", "Settings", b2 =>
                                {
                                    b2.Property<Guid>("CvDocumentCvId");

                                    b2.Property<string>("CvLanguage")
                                        .IsRequired();

                                    b2.Property<string>("FontFamily")
                                        .IsRequired();

                                    b2.Property<double>("FontScale");

                                    b2.PrimitiveCollection<string>("HiddenSections")
                                        .IsRequired();

                                    b2.Property<string>("PrimaryColor")
                                        .IsRequired();

                                    b2.Property<string>("SecondaryColor")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("SectionOrder")
                                        .IsRequired();

                                    b2.Property<string>("Spacing")
                                        .IsRequired();

                                    b2.HasKey("CvDocumentCvId");

                                    b2.ToTable("Cvs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvDocumentCvId");
                                });

                            b1.OwnsMany("CvForge.Api.Domain.EducationEntry", "Education", b2 =>
                                {
                                    b2.Property<Guid>("CvDocumentCvId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("City")
                                        .IsRequired();

                                    b2.Property<string>("Country")
                                        .IsRequired();

                                    b2.Property<string>("Degree")
                                        .IsRequired();

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<string>("GraduationYear")
                                        .IsRequired();

                                    b2.Property<string>("School")
                                        .IsRequired();

                                    b2.HasKey("CvDocumentCvId", "__synthesizedOrdinal");

                                    b2.ToTable("Cvs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvDocumentCvId");
                                });

                            b1.OwnsMany("CvForge.Api.Domain.Experience", "Experiences", b2 =>
                                {
                                    b2.Property<Guid>("CvDocumentCvId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.PrimitiveCollection<string>("Achievements")
                                        .IsRequired();

                                    b2.Property<string>("City")
                                        .IsRequired();

                                    b2.Property<string>("Company")
                                        .IsRequired();

                                    b2.Property<string>("Country")
                                        .IsRequired();

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<string>("EndDate");

                                    b2.Property<bool>("IsCurrent");

                                    b2.PrimitiveCollection<string>("Missions")
                                        .IsRequired();

                                    b2.Property<string>("Position")
                                        .IsRequired();

                                    b2.Property<string>("StartDate")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("Technologies")
                                        .IsRequired();

                                    b2.HasKey("CvDocumentCvId", "__synthesizedOrdinal");

                                    b2.ToTable("Cvs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvDocumentCvId");
                                });

                            b1.OwnsMany("CvForge.Api.Domain.LanguageEntry", "Languages", b2 =>
                                {
                                    b2.Property<Guid>("CvDocumentCvId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Level")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.HasKey("CvDocumentCvId", "__synthesizedOrdinal");

                                    b2.ToTable("Cvs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvDocumentCvId");
                                });

                            b1.OwnsMany("CvForge.Api.Domain.Project", "Projects", b2 =>
                                {
                                    b2.Property<Guid>("CvDocumentCvId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Date")
                                        .IsRequired();

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<string>("Role")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("Technologies")
                                        .IsRequired();

                                    b2.Property<string>("Url")
                                        .IsRequired();

                                    b2.HasKey("CvDocumentCvId", "__synthesizedOrdinal");

                                    b2.ToTable("Cvs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvDocumentCvId");
                                });

                            b1.OwnsMany("CvForge.Api.Domain.SkillCategory", "SkillCategories", b2 =>
                                {
                                    b2.Property<Guid>("CvDocumentCvId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate();

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("Skills")
                                        .IsRequired();

                                    b2.HasKey("CvDocumentCvId", "__synthesizedOrdinal");

                                    b2.ToTable("Cvs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvDocumentCvId");
                                });

                            b1.Navigation("Certifications");

                            b1.Navigation("Education");

                            b1.Navigation("Experiences");

                            b1.Navigation("Languages");

                            b1.Navigation("PersonalInfo")
                                .IsRequired();

                            b1.Navigation("Projects");

                            b1.Navigation("Settings")
                                .IsRequired();

                            b1.Navigation("SkillCategories");
                        });

                    b.Navigation("Document")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CvForge.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CvForge.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CvForge.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CvForge.Api.Domain.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
